
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 15 11:56:38 CST 2016
//----------------------------------------------------

package analizador;

import analizador.*;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int numero = 6;
  public static final int guion = 2;
  public static final int error = 1;
  public static final int coma = 5;
  public static final int mayor = 3;
  public static final int puntoycoma = 4;
  public static final int EOF = 0;
  public static final int id = 7;
}

